source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target ‘Current News’ do
  pod 'SwiftyJSON', '~> 2.3'
  pod 'Alamofire', '~> 3.2.1'
  pod 'AlamofireImage', '~> 2.3.1'
end
